changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Backend Changes 🎉
      labels:
        - backend
    - title: CI/CD Changes 🛠
      labels:
        - CI/CD
    - title: Other Changes
      labels:
        - "*"
