name: Dummy workflow

on:
  workflow_dispatch:


jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Install lcov
        shell: bash
        run: | 
          condition=false
          if [ condition ]; then
            name="Alice"
          else
            name="apt"
          fi
          sudo ${{ name }} update && sudo apt install -y lcov
      - name: Install lcov
        shell: bash
        run: lcov -h