name: Dummy workflow

on:
  workflow_dispatch:


jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Install lcov
        shell: bash
        run: | 
          condition=false
          com=$([ "$condition" = true ] && echo "Alice" || echo "apt")
          sudo ${{ com }} update && sudo apt install -y lcov
      - name: Install lcov
        shell: bash
        run: lcov -h