name: Make latest release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Release to make latest'
        required: false

jobs:
  wait-for-approvals:
    runs-on: ubuntu-latest
    if: ${{ 'success' == 'success' }}
    # environment: local

    steps:
      - name: Approval granted
        id: step1
        run: echo "set_prod_deploy=test 123" >> $GITHUB_ENV

  wait-for-approvals-2:
    runs-on: ubuntu-latest
    needs: wait-for-approvals
    if: ${{ 'success' == 'not success' }}
    # environment: local

    steps:
      - name: Approval granted
        id: step1
        run: echo "set_prod_deploy=test 123" >> $GITHUB_ENV

  execute:
    runs-on: ubuntu-latest
    if: ${{ always() && 'true' == 'true' }}
    needs: [wait-for-approvals,wait-for-approvals-2]
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Print output
        run: echo "Output ${env.set_prod_deploy}"
    
      - name: Update release to latest
        uses: ncipollo/release-action@v1.12.0
        with:
          name: ${{ github.ref }}
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: true
          allowUpdates: true
          omitBodyDuringUpdate: true