on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Release to make latest'
        required: true

jobs:
  wait-for-approvals:
    runs-on: ubuntu-latest
    if: ${{ 'false' == 'success' }}

    steps:
      - name: Approval granted
        run: echo "Received necessary approval, continuing."

  execute:
    runs-on: ubuntu-latest
    needs: wait-for-approvals
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      - name: Update release to latest
        uses: ncipollo/release-action@v1.12.0
        with:
          name: ${{ inputs.ref }}
          tag: ${{ inputs.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: true
          allowUpdates: true
          omitBodyDuringUpdate: true