name: Make latest release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Release to make latest'
        required: false

jobs:
  wait-for-approvals:
    runs-on: ubuntu-latest
    if: ${{ 'success' == 'success' }}
    # environment: local

    steps:
      - name: Approval granted
        id: step-1
        run: echo "set-prod-deploy=test 123" >> $GITHUB_OUTPUT

  execute:
    runs-on: ubuntu-latest
    needs: wait-for-approvals
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Print output
        run: echo "Output ${steps.step-1.set-prod-deploy}"
    
      - name: Update release to latest
        uses: ncipollo/release-action@v1.12.0
        with:
          name: ${{ github.ref }}
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: true
          allowUpdates: true
          omitBodyDuringUpdate: true

  send-slack-message:
    uses: ./.github/workflows/send-slack-notification.yml
    needs: execute
    secrets: inherit
    with:
      environment: local
      slack_channel: energy-digital-backend-releases
      payload: |
        {
          "text": "[LOCAL] Release ${{ github.ref_name }} has been deployed",
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*[LOCAL] Release `${{ github.ref_name }}` has been deployed 🚀*"
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "• Workflow execution: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Github workflow run>\n• See what changed: <${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}|Github release page>"
              }
            }
          ]
        }