on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Release to make latest'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      - name: Update release to latest
        uses: ncipollo/release-action@v1.12.0
        with:
          name: ${{ inputs.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: true
          allowUpdates: true