name: Trigger Pipeline on release

on:
  workflow_run:
    workflows: ["Backend stage tag triggered deployment"]
    types:
      - completed

jobs:
  check-workflow-status:
    runs-on: ubuntu-latest

    steps:
      - name: Check triggering workflow status
        id: check-condition
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
            echo "Triggering workflow finished with status '${{ github.event.workflow_run.conclusion }}'. Aborting current workflow."
            exit 1
          else
            echo "Triggering workflow finished with status '${{ github.event.workflow_run.conclusion }}'. Continuing current workflow."
          fi

  build:
    runs-on: ubuntu-latest
    needs: check-workflow-status
    permissions:
      contents: write

    steps:
      - name: Fetch release name
        env:
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          echo "TAG_NAME=$HEAD_BRANCH" >> $GITHUB_ENV
          echo "Tag to deploy: $HEAD_BRANCH"

      - name: Update release to latest
        uses: ncipollo/release-action@v1.12.0
        with:
          name: ${{ env.TAG_NAME }}
          tag: ${{ env.TAG_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: true
          allowUpdates: true
          omitBodyDuringUpdate: true


