name: Trigger Pipeline on release

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: print-tag-name
        run: |
          REF_NAME="${GITHUB_REF}"
          echo "Current Ref: $REF_NAME"
