name: Trigger Pipeline on release

on:
  workflow_run:
    workflows: ["Tag triggered stage deployment"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write

    steps:
      - name: Print head_branch
        env:
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          echo "branch: $HEAD_BRANCH"
      
      - name: Print head_commit
        env:
          HEAD_COMMIT: ${{ github.event.workflow_run.head_commit }}
        run: |
          echo "commit: $HEAD_COMMIT"
  
      - name: Checkout triggering workflow repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Get release name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            name=$(gh release list --json tagName,isDraft,isPrerelease,createdAt --jq "sort_by(.createdAt) | reverse | [.[] | select(.isDraft == false) | select(.isPrerelease == true) | select(.tagName | startswith(\"@backend\")) | .tagName][0]")
            echo "tag_name=$name" >> $GITHUB_ENV
            echo "Tag to deploy: $name"


