name: Trigger Pipeline on release

on:
  workflow_run:
    workflows: [StageDeployment]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: print-tag-name
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          echo "Current Ref: $REF_NAME"
