name: Trigger Pipeline on release

on:
  workflow_run:
    workflows: [StageDeployment]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout triggering workflow repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Output Tag Name
        run: echo "The tag name is ${{ github.event.client_payload.tag_name }}"

