name: Trigger Pipeline on release

on:
  workflow_run:
    workflows: ["Backend stage tag triggered deployment"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write

    steps:
      - name: Fetch release name
        env:
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          echo "TAG_NAME=$HEAD_BRANCH" >> $GITHUB_ENV
          echo "Tag to deploy: $HEAD_BRANCH"

      - name: Update release to latest
        uses: ncipollo/release-action@v1.12.0
        with:
          name: ${{ env.TAG_NAME }}
          tag: ${{ env.TAG_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: true
          allowUpdates: true
          omitBodyDuringUpdate: true


