name: Send slack notification

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: Github environment that holds the secrets
        required: true
      slack_channel:
        type: string
        description: Slack channel that will receive the message
        required: true
      payload:
        type: string
        description: Block kit message to be displayed
        required: true
      

jobs:
  send-slack-notification:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v3
    
      - name: Send slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ inputs.slack_channel }}
          payload: ${{ inputs.payload }}
        env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
            RELEASE_NAME: ${{ inputs.tag_name }}