name: Trigger Pipeline on Tag Creation

on:
  push:
    tags:
      - '@backend/v[0-9]*.[0-9]*.[0-9]*'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: print-tag-name
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "Current Tag Name: $TAG_NAME"

      - name: Get previous tag
        id: previousTag
        run: |
            name=$(git --no-pager tag --sort=creatordate --list '@backend/v*' | tail -2 | head -1)
            echo "previousTag=$name" >> $GITHUB_ENV
            echo "Previous Tag: $name"
 
      # Generate change log based on the PRs merged between the previous release and the current one
      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          toTag: ${{ github.ref_name }}
          fromTag: ${{ env.previousTag }}
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\nFull Changelog: #{{RELEASE_DIFF}}",
              "sort": "ASC",
              "pr_template": "- #{{TITLE}} by @#{{AUTHOR}} in ##{{NUMBER}}",
              "categories": [
              {
                "title": "## What's Changed",
                "labels": ["backend","CI/CD","infra"]
              }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Create release
      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true