name: Trigger Pipeline on Tag Creation

on:
  push:
    tags:
      - '@backend/v[0-9]+\.[0-9]+\.[0-9]+$'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: print-tag-name
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "Tag Name: $TAG_NAME"