name: Trigger Pipeline on Tag Creation

on:
  push:
    tags:
      - '@backend/v[0-9]*.[0-9]*.[0-9]*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: print-tag-name
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "Current Tag Name: $TAG_NAME"

      - name: Get previous tag
        id: previousTag
        run: |
            name=$(git --no-pager tag --sort=creatordate --list '@backend/v[0-9]*.[0-9]*.[0-9]*' | tail -2 | head -1)
            echo "previousTag=$name" >> $GITHUB_ENV
            echo "Previous Tag: $name"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
            gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${tag#v}" \
            --notes-start-tag="$previousTag" \
            --prerelease \
            --generate-notes
      # Later we'll use `gh release edit "$tag" --prerelease=false --latest` to update this release
