name: StageDeployment

on:
  push:
    tags:
      - '@backend/v[0-9]*.[0-9]*.[0-9]*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: print-tag-name
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "Current Tag Name: $TAG_NAME"

      - name: Get previous tag
        id: previousTag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURRENT_TAG: ${{ github.ref_name }}
        run: |
            name=$(gh release list --json tagName,isDraft,createdAt --jq "sort_by(.createdAt) | reverse | [.[] | select(.isDraft == false) | select(.tagName | startswith(\"@backend\")) | select(.tagName != \"${CURRENT_TAG}\") | .tagName][0]")
            echo "previousTag=$name" >> $GITHUB_ENV
            echo "Previous Tag: $name"

      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: "./.github/release-configuration.json"
          fromTag: ${{ env.previousTag }}
          toTag: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: print-changelog
        env:
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
        run: |
          echo "Changelog: $CHANGELOG"

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
